server:
  port: 10031

spring:
  application:
    name: dubbo-web
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  main:
    allow-bean-definition-overriding: true

dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://127.0.0.1
  cloud:
    subscribed-services: dubbo-service
  # 如果存在服务间循环依赖，可以考虑关闭检查
  #consumer:
    #check: false