server:
  port: 10030

spring:
  application:
    name: dubbo-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  main:
    allow-bean-definition-overriding: true

dubbo:
  scan:
    base-packages: com.happy.home.dubbo.service.api #指定 Dubbo 服务实现类的扫描基准包
  protocol: #Dubbo服务暴露的协议配置，其中子属性name为协议名称，port为协议端口（-1 表示自增端口，从 20880 开始）
    name: dubbo
    port: -1
  registry: #Dubbo 服务注册中心配置，其中子属性address 的值 "spring-cloud://127.0.0.1"，说明挂载到 Spring Cloud 注册中心
    address: spring-cloud://127.0.0.1